### ISSUE TITLE
Make babel a dev dependency

### ISSUE THREAD

**Issue by aleclarson** [semantic-release/travis-deploy-once#104]
Why is Babel transpilation done on-the-fly instead of before this package is published?

This package is [~12 MB](https://packagephobia.now.sh/result?p=travis-deploy-once) because of it.

**Comment by pvdlg** [comment]
We use `babel-register` as it makes development easier and avoid to have a build step.

We won't make any changes at that point as this library is mostly deprecated as Travis support [Build Stages](https://docs.travis-ci.com/user/build-stages). We recommend to use Build Stages and completely drop this library.

**Comment by aleclarson** [comment]
> We recommend to use Build Stages and completely drop this library.

Comparing `travis-deploy-once`..
```yaml
script: yarn build && yarn test
after_success:
  - travis-deploy-once "semantic-release"
```
..to Travis build stages..
```yaml
script: yarn build && yarn test
jobs:
  include:
    - stage: deploy
      script: yarn build && semantic-release
```
..I think there's still a place for `travis-deploy-once`.

&nbsp;

> We use `babel-register` as it makes development easier and avoid to have a build step.

Sure, but at the expense of your users. 😕 Is a build step really so bad?
