### ISSUE TITLE
Failing silently causing false positive builds.

### ISSUE THREAD

**Issue by pedro-mass** [semantic-release/travis-deploy-once#67]
Ran through setup with the CLI (https://github.com/semantic-release/cli), and it added to `travis.yml`
```yaml
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
```
When it errors, it's not bubbling up the error code and Travis thinks everything succeeded (but it didn't).

Was there a config setting that needs to be set to bubble up the error and cause the build to correctly fail?

**Comment by pedro-mass** [comment]
Updating to use a proper deploy script seems to get the error to fail the build

```yaml
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run travis-deploy-once "npm run semantic-release"
  on:
    branch: master
```
